namespace Settex.Build;

using Microsoft.Build.Framework;
using Microsoft.Build.Utilities;
using Settex.Compilation;

/// <summary>
///     MSBuild task to compile .settex files to appsettings*.json files.
/// </summary>
public class CompileSettexTask : Task
{
    /// <summary>
    ///     Gets or sets the path to the .settex source file.
    /// </summary>
    [Required]
    public string SourceFile { get; set; } = string.Empty;

    /// <summary>
    ///     Gets or sets the output directory where appsettings*.json files will be written.
    /// </summary>
    [Required]
    public string OutputDirectory { get; set; } = string.Empty;

    /// <summary>
    ///     Gets the list of files generated by the compilation.
    /// </summary>
    [Output]
    public ITaskItem[] GeneratedFiles { get; private set; } = Array.Empty<ITaskItem>();

    /// <summary>
    ///     Executes the task.
    /// </summary>
    /// <returns>True if the task succeeded, false otherwise.</returns>
    public override bool Execute()
    {
        try
        {
            this.Log.LogMessage(MessageImportance.Normal, $"Compiling Settex file: {this.SourceFile}");

            var compiler = new SettexCompiler();
            var result = compiler.Compile(this.SourceFile, this.OutputDirectory);

            // Log all diagnostics
            foreach (var diagnostic in result.Diagnostics)
            {
                this.LogDiagnostic(diagnostic);
            }

            if (!result.Success)
            {
                this.Log.LogError($"Settex compilation failed for {this.SourceFile}");
                return false;
            }

            // Collect generated files
            var generatedFiles = new List<ITaskItem>();
            var baseFile = Path.Combine(this.OutputDirectory, "appsettings.json");
            if (File.Exists(baseFile))
            {
                generatedFiles.Add(new TaskItem(baseFile));
            }

            // Add environment-specific files
            var envFiles = Directory.GetFiles(this.OutputDirectory, "appsettings.*.json");
            foreach (var envFile in envFiles)
            {
                generatedFiles.Add(new TaskItem(envFile));
            }

            this.GeneratedFiles = generatedFiles.ToArray();

            this.Log.LogMessage(MessageImportance.High, $"Successfully compiled {this.SourceFile} → {generatedFiles.Count} file(s)");
            return true;
        }
        catch (Exception ex)
        {
            this.Log.LogErrorFromException(ex, showStackTrace: true);
            return false;
        }
    }

    private void LogDiagnostic(Diagnostic diagnostic)
    {
        var message = diagnostic.Message;
        var file = this.SourceFile;
        int line = 0;
        int column = 0;

        if (diagnostic.Location != null)
        {
            line = diagnostic.Location.Line;
            column = diagnostic.Location.Column;
        }

        switch (diagnostic.Severity)
        {
            case DiagnosticSeverity.Error:
                this.Log.LogError(
                    subcategory: null,
                    errorCode: "SETTEX",
                    helpKeyword: null,
                    file: file,
                    lineNumber: line,
                    columnNumber: column,
                    endLineNumber: line,
                    endColumnNumber: column,
                    message: message);
                break;

            case DiagnosticSeverity.Warning:
                this.Log.LogWarning(
                    subcategory: null,
                    warningCode: "SETTEX",
                    helpKeyword: null,
                    file: file,
                    lineNumber: line,
                    columnNumber: column,
                    endLineNumber: line,
                    endColumnNumber: column,
                    message: message);
                break;

            case DiagnosticSeverity.Info:
                this.Log.LogMessage(
                    subcategory: null,
                    code: "SETTEX",
                    helpKeyword: null,
                    file: file,
                    lineNumber: line,
                    columnNumber: column,
                    endLineNumber: line,
                    endColumnNumber: column,
                    importance: MessageImportance.Normal,
                    message: message);
                break;
        }
    }
}
